/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2021.formulaUno;

import it.unicam.cs.pa2021.formulaUno.controller.Controller;
import it.unicam.cs.pa2021.formulaUno.controller.SimpleController;
import it.unicam.cs.pa2021.formulaUno.model.BasicGameField;
import it.unicam.cs.pa2021.formulaUno.model.CircuitReaderBasic;
import it.unicam.cs.pa2021.formulaUno.model.GridLocation;
import it.unicam.cs.pa2021.formulaUno.model.Player;
import it.unicam.cs.pa2021.formulaUno.model.creator.BasicGameFieldCreator;
import it.unicam.cs.pa2021.formulaUno.model.creator.BotPlayerCreator;
import it.unicam.cs.pa2021.formulaUno.model.creator.GameFieldCreator;
import it.unicam.cs.pa2021.formulaUno.model.creator.PlayerCreator;
import it.unicam.cs.pa2021.formulaUno.model.printer.BasicGameFieldPrinter;
import it.unicam.cs.pa2021.formulaUno.model.printer.GameFieldPrinter;
import it.unicam.cs.pa2021.formulaUno.view.ConsoleView;
import it.unicam.cs.pa2021.formulaUno.view.View;

import java.io.*;
import java.util.Optional;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {
        menu();
        Scanner in = new Scanner(System.in);
        CircuitReaderBasic readerBasic = getCircuitReaderBasic(in);

        PlayerCreator<GridLocation> playerCreator = new BotPlayerCreator<>();
        GameFieldCreator<GridLocation> gameFieldCreator = new BasicGameFieldCreator(playerCreator);
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));

        GameFieldPrinter<BasicGameField, GridLocation> printer = new BasicGameFieldPrinter();
        BasicGameField field = createGameField(readerBasic, gameFieldCreator);
        View<BasicGameField, GridLocation> view = new ConsoleView<>(bufferedReader, printer);
        Controller<BasicGameField, GridLocation> controller = setController(field, view);
        controller.viewGameField();

        race(in, controller);
    }

    /**
     * Scelta del circuito dal quale vedere la corsa.
     * @param in scanner per l'input dell'utente.
     * @return il reader appena creato.
     * @throws FileNotFoundException
     */
    private static CircuitReaderBasic getCircuitReaderBasic(Scanner in) throws FileNotFoundException {
        CircuitReaderBasic readerBasic;
        int choice = in.nextInt();
        if (choice == 1)
            readerBasic = initApp("circuito.txt");
        else if (choice == 2)
            readerBasic = initApp("circuitoLineare.txt");
        else
            throw new IllegalArgumentException("Devi digitare solamente uno dei numeri richiesti");
        return readerBasic;
    }

    /**
     * Stampa ogni turno della gara (ogni volta che l'utente preme il tasto 0) fino a che non ci sia un vincitore (o che tutti vadano fuori pista).
     * @param in scanner utile all'utente per scrivere da tastiera.
     * @param controller controller dell'applicazione.
     */
    private static void race(Scanner in, Controller<BasicGameField, GridLocation> controller) {
        while (controller.getGameField().getState()) {
            System.out.println("Premi 0 per continuare al prossimo turno");
            if (in.nextInt() == 0) {
                for (Player<GridLocation> pl : controller.getGameField().getPlayers()) {
                    if (pl.getCar().isInRace())
                        controller.addMove(pl.moveCarTo(Optional.empty()));
                }
                controller.nextStage();
                controller.viewGameField();
            }
        }
        controller.closeView();
    }

    /**
     * Crea e restituisce un game field da usare nell'applicazione.
     * @param readerBasic generatore del circuito del game field.
     * @param gameFieldCreator creator responsabile della creazione del game field.
     * @return il game field appena creato.
     * @throws IOException
     */
    private static BasicGameField createGameField(CircuitReaderBasic readerBasic, GameFieldCreator<GridLocation> gameFieldCreator) throws IOException {
        int[][] track = readerBasic.createCircuit();
        int height = readerBasic.getTrackHeight();
        int width = readerBasic.getTrackWidth();
        return (BasicGameField) gameFieldCreator.createGameField(width, height, track, readerBasic.namePlayers());
    }

    /**
     * Inizializzatore del controller.
     * @param field game field da associare al controller.
     * @param view view da associare al controller.
     * @return controller appena creato.
     */
    private static Controller<BasicGameField, GridLocation> setController(BasicGameField field, View<BasicGameField, GridLocation> view) {
        Controller<BasicGameField, GridLocation> controller = new SimpleController<>(field);
        controller.recordView(view);
        return controller;
    }

    private static void menu() {
        System.out.println("****************************************************");
        System.out.println("**                  FORMULA UNO                   **");
        System.out.println("Ciao, prima di iniziare a giocare scegli un circuito");
        System.out.println("Digita 1 : circuito (piccolo, 3 giocatori)");
        System.out.println("Digita 2 : circuitoLineare (medio, 4 giocatori)");
    }

    /**
     * Metodo che serve ad inizializzare il reader.
     * @param fileName nome del file da cui prendere il circuito.
     * @return il nuovo reader.
     * @throws FileNotFoundException
     */
    private static CircuitReaderBasic initApp(String fileName) throws FileNotFoundException {
        File file = new File(fileName);
        FileReader fileReader = new FileReader(file);
        return new CircuitReaderBasic(fileReader);
    }
}
